# Nome: Pedro Fernando Christofoletti dos Santos
# NUSP: 11218560

all:
	@gcc main.c complex_sparse.c -o complex_sparse_cube -I. 

run:
	@./complex_sparse_cube

clean:
	rm *.o

zip:
	zip -r Complex_sparse_cube.zip *.c *.h Makefile