# Nome: Pedro Fernando Christofoletti dos Santos
# NUSP: 11218560

all:
	@gcc main.c complex_sparse.c -o complex_sparse -I. 

run:
	@./complex_sparse

clean:
	rm *.o

zip:
	zip -r THIS_IS_SPARSA.zip *.c *.h Makefile